

package com.core_server.sals.repository;

import com.core_server.sals.entity.Attendance;
import com.core_server.sals.entity.ClassSession;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;


import java.time.LocalDateTime;
import java.util.List;

public interface AttendanceRepository extends JpaRepository<Attendance, Long> {

    // QUERY: Counts unique class sessions where the student was marked 'PRESENT' for a specific subject.
    // METHOD: Used to calculate the numerator for a student's attendance percentage.
    @Query("SELECT COUNT(DISTINCT a.session.id) FROM Attendance a WHERE a.studentId = :studentId AND a.session.subject.id = :subjectId AND a.status = 'PRESENT'")
    int countByStudentIdAndSubjectId(@Param("studentId") String studentId, @Param("subjectId") Long subjectId);

    // QUERY: Auto-generated by Spring to find records matching a student ID within a time range, sorted newest first.
    // METHOD: Used to populate the student's daily activity timeline on their dashboard.
    List<Attendance> findByStudentIdAndTimestampBetweenOrderByTimestampDesc(String studentId, LocalDateTime startOfDay, LocalDateTime endOfDay);

    // QUERY: Auto-generated by Spring to return true/false if a record exists for this student and session.
    // METHOD: Used as a security check to prevent a student from scanning the same QR code twice.
    boolean existsByStudentIdAndSession(String studentId, ClassSession session);

     //QUERY: Auto-generated by Spring to find all attendance logs linked to a specific string session identifier.
    // METHOD: Used by the teacher's dashboard to display the live, scrolling list of students who just scanned in.
    List<Attendance> findBySession_SessionIdentifierOrderByTimestampDesc(String sessionIdentifier);

    // QUERY: Auto-generated by Spring to count the total number of rows matching a specific session ID.
    // METHOD: Used to quickly display the "Total Present" number on the teacher's active session screen.
    long countBySession_Id(Long sessionId);


    // QUERY: Groups records by student ID, returning their ID, total classes attended, and their most recent scan time for a specific teacher.
    // METHOD: Used to populate the teacher's "Analytics" or "Student List" table with aggregate data.
    @Query("SELECT a.studentId, COUNT(a.id), MAX(a.timestamp) FROM Attendance a WHERE a.session.teacherId = :teacherId GROUP BY a.studentId")
    List<Object[]> findStudentStatsForTeacher(@Param("teacherId") String teacherId);
}